CREATE TABLE PHONGBAN (
    MAPB VARCHAR2(10) PRIMARY KEY,
    TENPB VARCHAR2(100) NOT NULL,
    MAPB_CHA VARCHAR2(10),
    CONSTRAINT FK_PHONGBAN_CHA 
        FOREIGN KEY (MAPB_CHA) REFERENCES PHONGBAN(MAPB)
);

CREATE TABLE NHANVIEN (
    MANV VARCHAR2(10) PRIMARY KEY,
    HOTEN VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    MAPB VARCHAR2(10),
    CHUCVU VARCHAR2(50),
    LUONG NUMBER(12,2),
    NGAYPHEP_CONLAI NUMBER DEFAULT 12,
    MANV_QUANLY VARCHAR2(10),
    CONSTRAINT FK_NV_PB FOREIGN KEY (MAPB) REFERENCES PHONGBAN(MAPB),
    CONSTRAINT FK_NV_QUANLY FOREIGN KEY (MANV_QUANLY) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE CHAMCONG (
    MACC VARCHAR2(10) PRIMARY KEY,
    MANV VARCHAR2(10),
    NGAY DATE,
    GIOVAO TIMESTAMP,
    GIORA TIMESTAMP,
    SOGIO NUMBER(4,2),
    CONSTRAINT FK_CC_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);

CREATE TABLE LICHSU_PHEP (
    MALICHSU VARCHAR2(30) PRIMARY KEY,
    MANV VARCHAR2(10),
    MA_DON VARCHAR2(30),
    SO_NGAY_TRU NUMBER,
    NGAY_XULY DATE,
    GHICHU VARCHAR2(255),
    CONSTRAINT FK_LSP_NV FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);
